import { readdirSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import type { SupabaseClient } from '@supabase/supabase-js'
import { describe, expect, it } from 'vitest'
import type { Database } from '@/lib/database.types'
import { supabase } from '@/lib/supabase'

/**
 * The generated schema types, and the wiring that makes them matter.
 *
 * `src/lib/database.types.ts` is checked in and regenerated by CI on every
 * migration (the `db-types` job). This asserts two things it cannot: that the
 * file still lists every table the migrations leave standing — so a `git diff`
 * failure in CI has a matching local signal — and that the client is
 * parameterised with `Database`, without which the file is decorative and no
 * query builder is checked against the schema.
 */

const MIGRATIONS = resolve(process.cwd(), 'supabase/migrations')
const TYPES_FILE = resolve(process.cwd(), 'src/lib/database.types.ts')

/** The public tables a fresh project ends up with, replaying the migrations. */
function liveTables(): Set<string> {
  const create = /create table if not exists public\.(\w+)/g
  const drop = /drop table if exists public\.(\w+)/g
  const tables = new Set<string>()
  for (const file of readdirSync(MIGRATIONS).sort()) {
    const sql = readFileSync(resolve(MIGRATIONS, file), 'utf8')
    for (const match of sql.matchAll(create)) if (match[1]) tables.add(match[1])
    for (const match of sql.matchAll(drop)) if (match[1]) tables.delete(match[1])
  }
  return tables
}

/** The table names the generated file exposes under `Tables`. */
function generatedTables(): Set<string> {
  const source = readFileSync(TYPES_FILE, 'utf8')
  const block = /Tables: \{\n([\s\S]*?)\n {4}\}\n {4}Views:/.exec(source)?.[1] ?? ''
  const names = [...block.matchAll(/^ {6}(\w+): \{$/gm)].map((match) => match[1] ?? '')
  return new Set(names.filter(Boolean))
}

describe('generated database types', () => {
  it('covers exactly the tables the migrations leave standing', () => {
    const live = liveTables()
    // Guards the guard: a parser that matched nothing would pass vacuously.
    expect(live.size).toBeGreaterThan(3)
    expect([...generatedTables()].sort()).toEqual([...live].sort())
  })

  it('is regenerated and diff-checked by CI', () => {
    const workflow = readFileSync(resolve(process.cwd(), '.github/workflows/ci.yml'), 'utf8')
    expect(workflow).toMatch(/npm run db:types/)
    expect(workflow).toMatch(/git diff --exit-code -- src\/lib\/database\.types\.ts/)
    const pkg = JSON.parse(readFileSync(resolve(process.cwd(), 'package.json'), 'utf8'))
    expect(pkg.scripts['db:types']).toBe('bash scripts/gen-db-types.sh')
  })

  it('parameterises the Supabase client with the generated schema', () => {
    // Compile-time: if the client ever drops <Database>, the query builders
    // stop being checked against the schema and this line fails tsc.
    const typed: SupabaseClient<Database> | null = supabase
    expect(typed).toBeNull() // no backend configured under test
  })
})
