import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import type { SupabaseClient } from '@supabase/supabase-js'
import { describe, expect, it } from 'vitest'
import type { Database } from '@/lib/database.types'
import { supabase } from '@/lib/supabase'

/**
 * The generated schema types, checked against the migrations.
 *
 * `src/lib/database.types.ts` is generated by `npm run db:types` and committed.
 * A migration that adds, drops or renames a column has to regenerate it in the
 * same commit; nothing but this test enforces that. It replays the migrations —
 * the `create table` columns, the `add column` / `drop column` alters, the
 * `drop table`s — and asserts the generated file's `Row` types name exactly the
 * columns that survive. A column retyped in place (int → text) slips through,
 * but that is the rare case, and sync.ts already folds the columns where it
 * would bite onto a known shape at read time.
 */

const MIGRATIONS = resolve(process.cwd(), 'supabase/migrations')
const TYPES_FILE = resolve(process.cwd(), 'src/lib/database.types.ts')

const CONSTRAINT_KEYWORDS = new Set([
  'primary',
  'foreign',
  'unique',
  'check',
  'constraint',
  'exclude',
])

/** Split a `create table (...)` body on the commas that separate its members. */
function splitMembers(body: string): string[] {
  const parts: string[] = []
  let depth = 0
  let current = ''
  for (const char of body) {
    if (char === '(') depth += 1
    else if (char === ')') depth -= 1
    if (char === ',' && depth === 0) {
      parts.push(current)
      current = ''
    } else {
      current += char
    }
  }
  if (current.trim()) parts.push(current)
  return parts
}

/** `{ table: Set<column> }` a fresh project ends up with, replaying the migrations. */
function schemaFromMigrations(): Map<string, Set<string>> {
  const tables = new Map<string, Set<string>>()
  const createTable = /create table (?:if not exists )?public\.(\w+)\s*\(([\s\S]*?)\n\)\s*;/gi
  const addColumn = /alter table (?:only )?public\.(\w+)\s+add column (?:if not exists )?(\w+)/gi
  const dropColumn = /alter table (?:only )?public\.(\w+)\s+drop column (?:if exists )?(\w+)/gi
  const dropTable = /drop table (?:if exists )?public\.(\w+)/gi

  for (const file of readdirSync(MIGRATIONS).sort()) {
    const sql = readFileSync(resolve(MIGRATIONS, file), 'utf8').replace(/--[^\n]*/g, '')

    for (const match of sql.matchAll(createTable)) {
      const [, name, body] = match
      if (!name || body === undefined) continue
      const columns = new Set<string>()
      for (const member of splitMembers(body)) {
        const first = member.trim().split(/\s+/)[0]
        if (!first || CONSTRAINT_KEYWORDS.has(first.toLowerCase())) continue
        columns.add(first)
      }
      tables.set(name, columns)
    }
    for (const match of sql.matchAll(addColumn)) {
      if (match[1] && match[2]) tables.get(match[1])?.add(match[2])
    }
    for (const match of sql.matchAll(dropColumn)) {
      if (match[1] && match[2]) tables.get(match[1])?.delete(match[2])
    }
    for (const match of sql.matchAll(dropTable)) {
      if (match[1]) tables.delete(match[1])
    }
  }
  return tables
}

/** `{ table: Set<column> }` the generated file exposes under `Tables[...].Row`. */
function schemaFromGeneratedFile(): Map<string, Set<string>> {
  const source = readFileSync(TYPES_FILE, 'utf8')
  const block = /Tables: \{\n([\s\S]*?)\n {4}\}\n {4}Views:/.exec(source)?.[1] ?? ''
  const tables = new Map<string, Set<string>>()
  const tableBlock = /^ {6}(\w+): \{\n([\s\S]*?)\n {6}\}/gm
  for (const match of block.matchAll(tableBlock)) {
    const [, name, body] = match
    if (!name || body === undefined) continue
    const row = /Row: \{\n([\s\S]*?)\n {8}\}/.exec(body)?.[1] ?? ''
    const columns = new Set([...row.matchAll(/^ {10}(\w+):/gm)].map((c) => c[1]!))
    tables.set(name, columns)
  }
  return tables
}

/** Sorted plain object, so a mismatch prints readably. */
function sortedEntries(schema: Map<string, Set<string>>): Record<string, string[]> {
  return Object.fromEntries(
    [...schema].sort(([a], [b]) => a.localeCompare(b)).map(([t, c]) => [t, [...c].sort()]),
  )
}

describe('generated database types', () => {
  const fromMigrations = schemaFromMigrations()
  const fromFile = schemaFromGeneratedFile()

  it('parses a plausible schema out of the migrations', () => {
    // Guards the guard: a parser that matched nothing would pass every
    // comparison below vacuously.
    expect(fromMigrations.size).toBeGreaterThan(3)
    for (const [table, columns] of fromMigrations) {
      expect(columns.size, `${table} has no columns`).toBeGreaterThan(1)
    }
  })

  it('names exactly the tables and columns the migrations leave standing', () => {
    // One assertion over the whole shape: a renamed column shows as one added
    // and one removed, a dropped table as a missing key, all in one diff.
    expect(sortedEntries(fromFile)).toEqual(sortedEntries(fromMigrations))
  })

  it('can be regenerated with npm run db:types', () => {
    expect(existsSync(resolve(process.cwd(), 'scripts/gen-db-types.sh'))).toBe(true)
    const pkg = JSON.parse(readFileSync(resolve(process.cwd(), 'package.json'), 'utf8'))
    expect(pkg.scripts['db:types']).toBe('bash scripts/gen-db-types.sh')
  })

  it('parameterises the Supabase client with the generated schema', () => {
    // Compile-time: if the client ever drops <Database>, the query builders
    // stop being checked against the schema and this line fails tsc.
    const typed: SupabaseClient<Database> | null = supabase
    expect(typed).toBeNull() // no backend configured under test
  })
})
