import js from '@eslint/js'
import prettier from 'eslint-config-prettier'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import globals from 'globals'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  // supabase/.temp holds artefacts the CLI writes while a local stack runs, and
  // .lighthouseci the audit reports. Both are generated, both are minified, and
  // linting them fails the whole run for anyone with a stack up.
  {
    ignores: [
      'dist',
      'dist-ssr',
      'node_modules',
      'coverage',
      'public/stockfish',
      'supabase/.temp',
      '.lighthouseci',
      // Generated by scripts/gen-db-types.sh; linting it fails on the CLI's
      // own style, and reformatting would make CI's byte-for-byte diff fail.
      'src/lib/database.types.ts',
    ],
  },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [js.configs.recommended, ...tseslint.configs.recommended, prettier],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
  {
    // shadcn pairs a component with the cva() call that describes its variants,
    // in one file, and other components style themselves by importing that call
    // — a link that wants to look like a button asks for buttonVariants rather
    // than copying its classes. allowConstantExport does not cover it, because
    // the export is a function call and not a literal. Splitting each component
    // in two to satisfy the rule would fork every one of them from upstream, so
    // the named exports are allowed here instead, and only here.
    files: ['src/components/UI/**/*.tsx'],
    rules: {
      'react-refresh/only-export-components': [
        'warn',
        {
          allowConstantExport: true,
          // The cva() calls, plus the Radix primitives re-exported under the
          // project's own name — `const Dialog = DialogPrimitive.Root` is a
          // component, but an alias of an import is not something the rule can
          // see through.
          allowExportNames: [
            'buttonVariants',
            'badgeVariants',
            'Dialog',
            'DialogClose',
            'DialogPortal',
            'DialogTrigger',
            'Sheet',
            'SheetClose',
            'SheetPortal',
            'SheetTrigger',
          ],
        },
      ],
    },
  },
  {
    // Node config files and scripts: no JSX, no DOM.
    files: ['**/*.{js,mjs}'],
    extends: [js.configs.recommended, prettier],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: globals.node,
    },
  },
  {
    // Dev scripts also hold code passed to page.evaluate(), which runs in the
    // browser, so browser globals are legitimate there.
    files: ['scripts/**/*.mjs'],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
  },
)
